### ISSUE TITLE
Free compontents of mdast-react-render

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/styleguide#144]
## Feature Request

Remove `mdast-react-render` (function `renderMdast`) from following components:

* `Comment`
* `CommentTeaser`
* `TeaserFeed`

Suggestion is to allow components to accept plain text or HTML via props but not MDAST-like objects.

Goal is to have these components being able to handle more generic, unrelated to MDAST.

This is a breaking change.

**Comment by tpreusse** [comment]
The correct approach would be to accept `PropTypes.node`—a react node, which can also be a plain string. Accepting HTML is not a good idea, especially in the context of comments it could easily lead to an vulnerabilities from user content.

Generally I agree that it could be nice to extract the mdast call and accept plain text strings too. However this will require a refactor of `CommentTree` und it's usage in `republik-frontend`. Which is a good idea anyhow but a bigger project.  Maybe part of the next improvement of the comment system.

The `TeaserFeed` case is a bit different but similarly achievable. And a smaller refactor.

A much simpler and not-breaking approach would be to detect strings and directly render those.

However all-in-all this isn't a real feature and the benefit of supporting plain strings is theoretical for us. Might be useful for another user of the styleguide. The root issue was outdated documentation (addressed by https://github.com/orbiting/styleguide/pull/145).

If we want to do this it should be split into two cross repo issues: refactor comments and refactor feed.

**Comment by tpreusse** [comment]
`Comment` is no longer exported. `CommentTeaser` now takes a plain preview string. IMO no longer relevant. Reopen if you care.
