### ISSUE TITLE
AutosuggestField not usable in its current form

### ISSUE THREAD

**Issue by lukasbuenger** [orbiting/styleguide#40]
As of now, this component delegates to react-autocomplete while imperatively dumbing its feature catalogue down to the most simplistic of use cases, which you hardly ever come across when dealing with autosuggestion problems in real life. Even plain HTML selects are more flexible.

I'd expect a styled proxy for react-autocomplete, instead I get a fancy string-only select. In its current form not a worthy addition to this library. 

I will try to solve this in an upcoming PR but, tbh, was quite astonished by the fact that this got  released in the first place.

**Comment by tpreusse** [comment]
Agree. `AutosuggestField` is a leftover from the crowdfunding that we didn't even end up using. Was never part of the exposed API.

Have a look at the new dropdown:
https://styleguide.republik.ch/forms#dropdown

Ideally we'd build a AutoSuggest with it's internals & downshift.

**Comment by lukasbuenger** [comment]
Alright, will use downshift and the Dropdown then and post a draft of something autosuggesty asap. Thanks!
