### ISSUE TITLE
TeaserEmbedComment: Wrong link to origin comment

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/styleguide#415]
Article inline comment component (`TeaserEmbedComment`) links origin comment and authors profile page.

Origin comment link however points to article instead of comment on discussion page.

[see this article](https://www.republik.ch/2021/08/25/warum-wir-sie-bitten-links-zu-quellen-in-ihren-kommentaren-vorab-zu-pruefen)

**Comment by annatraussnig** [comment]
Solved
